// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Capabilities = { features: Array<string>, actions: Array<string>, tree_delta_supported: boolean, multi_session: boolean, max_request_size: number | null, };
