// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Capabilities = { features: Array<string>, actions: Array<string>, treeDeltaSupported: boolean, multiSession: boolean, maxRequestSize: number | null, };
