// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ClientInfo } from "./ClientInfo";

export type InitializeParams = { protocol_version: string, client_info: ClientInfo | null, capabilities: Capabilities | null, };
