// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ServerInfo } from "./ServerInfo";

export type InitializeResult = { sessionId: string, protocolVersion: string, negotiatedVersion: string, serverInfo: ServerInfo, capabilities: Capabilities, };
