// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "./Permission";

/**
 * Collection of permission grants held by a session.
 */
export type PermissionSet = { permissions: Array<Permission>, };
