// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single permission grant for a resource.
 */
export type Permission = { resource: string, read: boolean, write: boolean, delete: boolean, };
