// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional pre-action element validation.
 * When present, the extension validates the target element matches these criteria
 * before executing the action.
 */
export type Precondition = { 
/**
 * Expected tag name (case-insensitive, e.g. "BUTTON", "A")
 */
tagName: string | null, 
/**
 * Element text must include this substring
 */
textContains: string | null, 
/**
 * Attribute key-value pairs to match exactly
 */
attributes: { [key in string]?: string } | null, };
